### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by v1rtl** [vimlet/bundl#2]
When I try to use some custom transformer it throws an error.

```
Build started...
(node:18245) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.module.exports.getInputMatches (/home/v1rtl/Desktop/Coding/forks/bundl/plugins/bundl-plugin-babel/test/node_modules/@vimlet/bundl/src/lib/util.js:7:30)
    at Object.module.exports.process (/home/v1rtl/Desktop/Coding/forks/bundl/plugins/bundl-plugin-babel/test/node_modules/@vimlet/bundl/src/lib/transform.js:83:52)
    at /home/v1rtl/Desktop/Coding/forks/bundl/plugins/bundl-plugin-babel/test/node_modules/@vimlet/bundl/src/lib/pack.js:83:44
    at Array.forEach (<anonymous>)
    at build (/home/v1rtl/Desktop/Coding/forks/bundl/plugins/bundl-plugin-babel/test/node_modules/@vimlet/bundl/src/lib/pack.js:78:8)
    at pack (/home/v1rtl/Desktop/Coding/forks/bundl/plugins/bundl-plugin-babel/test/node_modules/@vimlet/bundl/src/lib/pack.js:21:9)
    at async Object.module.exports.build (/home/v1rtl/Desktop/Coding/forks/bundl/plugins/bundl-plugin-babel/test/node_modules/@vimlet/bundl/src/lib/pack.js:14:3)
    at async module.exports (/home/v1rtl/Desktop/Coding/forks/bundl/plugins/bundl-plugin-babel/test/node_modules/@vimlet/bundl/src/lib/cli.js:36:9)
(node:18245) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:18245) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 0.49s.
```

**plugin.js**

```js
const { transformAsync } = require('@babel/core')

module.exports = async (entry, opts) => {
  entry.content = (await transformAsync(entry.content, opts)).code
  return entry
}
```

**index.js**

```js
console.log('Hello World')
```

**package.json**

```
{
  "name": "test",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "@babel/core": "^7.5.5",
    "@babel/preset-env": "^7.5.5",
    "@vimlet/bundl": "^1.0.4"
  },
  "scripts": {
    "dev": "npx @vimlet/bundl"
  }
}
```

**bundl.config.js**

```js
const babel = require('./plugin') 

module.exports = {
  output: {
    'build/bundle.js': {
      use: entry => babel(entry, {
        presets: [require('@babel/preset-env')]
      })
    },
    input: 'src/**.js'
  }
}
```

**Comment by lethevimlet** [comment]
Input must go inside ouput key, also yesterday we fixed an issue where input: string wasn't supported, try using object instead.
```
const babel = require('./plugin') 

module.exports = {
  output: {
    'build/bundle.js': {
      use: entry => babel(entry, {
        presets: [require('@babel/preset-env')]
      }),
      input: {
        'src/**.js': true
      }
    }
  }
};
```
v1.0.5 fixes the problem and as soon we finish testing it will publish it.

**Comment by lethevimlet** [comment]
I upload a working example for your convenience.
[bundl-issue2.zip](https://github.com/vimlet/bundl/files/3472081/bundl-issue2.zip)

**Comment by lethevimlet** [comment]
I will add a more user friendly error message when output keys are provided without input.
I'm closing this issue since I believe it's solved. Feel free to re-open it if needed.

**Comment by v1rtl** [comment]
@lethevimlet, okay looking forward to new version! Will start writing plugins as soon as  v1.0.5 releases
